# Generated by Django 5.2 on 2025-04-12 12:11

import bgremover.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_image', models.ImageField(upload_to=bgremover.models.get_file_path)),
                ('processed_image', models.ImageField(blank=True, null=True, upload_to=bgremover.models.get_output_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
